# Generated by Django 4.1.2 on 2022-10-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_alter_time_project_alter_time_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='ended_at',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='time',
            name='started_at',
            field=models.DateTimeField(unique=True),
        ),
    ]
